services:
  api:
    build:
      context: ./api
      dockerfile: Containerfile
    environment:
      APP_HOST: api
      APP_PORT: 3000
      APP_ROOT: /api
      TZ: PST8PDT
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - backend

  ui:
    build:
      context: ./ui
      dockerfile: Containerfile
    depends_on:
      - api
    environment:
      EXPOSED_UI_PORT: 8090
      # EXPOSED_REDISCMD_PORT: 8099
      TZ: PST8PDT
    ports:
      - 8090:80
    restart: unless-stopped
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
