#!/usr/bin/bash

rm -fr .venv

python3 -m venv .venv

source .venv/bin/activate

python -m pip install --upgrade pip wheel

pip install -r ./api/requirements.txt

pip install -r ./api/requirements.dev.txt
