#!/usr/bin/bash

rm -fr .venv

python=python3
[ -f ~/opt/cpython/bin/python3.12 ] && python=~/opt/cpython/bin/python3.12

${python} -m venv .venv

source .venv/bin/activate

${python} -m pip install --upgrade pip wheel

hash -r pip

pip install -r ./api/requirements.txt

pip install -r ./api/requirements.dev.txt
