services:
  api:
    build:
      context: ./api
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_HOST: api
      APP_PORT: 3000
      APP_ROOT: /api
      TZ: PST8PDT
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - backend

  ui:
    build:
      context: ./ui
    environment:
      EXPOSED_UI_PORT: 8090
      EXPOSED_REDISCMD_PORT: 8099
      TZ: PST8PDT
    ports:
      - 8090:80
    restart: unless-stopped
    networks:
      - frontend
      - backend

  redis:
    image: eqalpha/keydb:latest
    environment:
      TZ: PST8PDT
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - backend

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      REDIS_HOSTS: local:redis:6379
      TZ: PST8PDT
    ports:
      - 8099:8081
    restart: unless-stopped
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
