version: '3.8'

services:
  api:
    build:
      context: ./api
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_HOST: api
      APP_PORT: 3000
      APP_ROOT: /api
    ports:
      - 3000:3000
    restart: always
    networks:
      - backend

  ui:
    build:
      context: ./ui
    environment:
      EXPOSED_API_PORT: 3000
      EXPOSED_UI_PORT: 8090
      EXPOSED_REDISCMD_PORT: 8099
    ports:
      - 8090:80
    restart: always
    networks:
      - frontend
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    restart: always
    networks:
      - backend

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8099:8081
    restart: always
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
