FROM node:current-alpine AS build

WORKDIR /app

RUN wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.shrc" SHELL="$(which sh)" sh

COPY pnpm-lock.yaml package.json /app/
COPY favicon.ico index.html tailwind.config.* tsconfig.* vite.config.* /app/
COPY src/ /app/src/

RUN source ~/.shrc && pnpm install && pnpm run build


FROM nginx:mainline-alpine
RUN apk upgrade --no-cache
RUN rm -fr /etc/nginx/conf.d

WORKDIR /

COPY --from=build /app/dist usr/share/nginx/html

COPY ./etc/nginx /etc/nginx
COPY ./etc/docker-entrypoint.d/*.sh /docker-entrypoint.d
