
FROM alpine

ARG ENABLE_TESTS

RUN apk add --no-cache curl

# Add non root user
RUN addgroup -S app && adduser app -S -G app

USER app:app

WORKDIR /app

ENV PATH=/home/app/.local/bin:$PATH

# set uv env vars
ENV UV_MANAGED_PYTHON=1 \
    UV_LINK_MODE=symlink

# install UV
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# install python
RUN uv python install 3.14

# copy project files to prepare for setup
COPY --chown=app:app pyproject.toml uv.lock /app/

# copy files
COPY --chown=app:app huntwordsapi/ /app/huntwordsapi/
 
# create .venv, install project dependencies, run tests if arg set
RUN -- if [ -n "$ENABLE_TESTS" ]; then \
uv sync --all-groups && \
ls -l .venv/ .venv/bin/ && \
uv run --frozen pytest huntwordsapi/ 2>&1 | tee .pytest.log && \
rm -fr .pytest_cache/ .venv; \
fi && \
uv sync --frozen --no-dev


EXPOSE 3000

CMD ["uv", "run", "--frozen", "python", "-m", "huntwordsapi"]
