
FROM alpine

RUN apk add --no-cache curl git

# Add non root user
RUN addgroup -S app && adduser app -S -G app

USER app:app

WORKDIR /app

ENV PATH=/home/app/.local/bin:$PATH

# set uv env vars
ENV UV_MANAGED_PYTHON=1 \
    UV_LINK_MODE=symlink

# install UV
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# install python
RUN uv python install 3.14

# install uvextras
RUN uv tool install https://github.com/klmcwhirter/uvextras.git

# copy project files to prepare for setup
COPY --chown=app:app pyproject.toml uv.lock /app/
COPY --chown=app:app .uvextras/ /app/.uvextras/
 
# create .venv, install project dependencies
RUN uvextras run create

# copy files
COPY --chown=app:app huntwordsapi/ /app/huntwordsapi/

# run tests
RUN uvextras run pytest && uvextras run allclean && uv sync --frozen --no-dev

EXPOSE 3000

CMD ["uv", "run", "python", "-m", "huntwordsapi"]
